// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgTULLceTfaCRYtw3OW8NJKnA-jFlYGFg',
    appId: '1:1057292899601:web:a6ebced28a671cb51168b0',
    messagingSenderId: '1057292899601',
    projectId: 'crud-project-1d07a',
    authDomain: 'crud-project-1d07a.firebaseapp.com',
    storageBucket: 'crud-project-1d07a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMLHMGORdtgS2UrSSCAOYLE9m6Ng9SQjk',
    appId: '1:1057292899601:android:062888bab95a30e91168b0',
    messagingSenderId: '1057292899601',
    projectId: 'crud-project-1d07a',
    storageBucket: 'crud-project-1d07a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq4bf4OurmeE6KXt5QLKG-GN1EfnlrEaA',
    appId: '1:1057292899601:ios:6a4e88af757f68391168b0',
    messagingSenderId: '1057292899601',
    projectId: 'crud-project-1d07a',
    storageBucket: 'crud-project-1d07a.appspot.com',
    iosBundleId: 'com.example.crudProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBq4bf4OurmeE6KXt5QLKG-GN1EfnlrEaA',
    appId: '1:1057292899601:ios:6a4e88af757f68391168b0',
    messagingSenderId: '1057292899601',
    projectId: 'crud-project-1d07a',
    storageBucket: 'crud-project-1d07a.appspot.com',
    iosBundleId: 'com.example.crudProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgTULLceTfaCRYtw3OW8NJKnA-jFlYGFg',
    appId: '1:1057292899601:web:57e9e5eb04c991be1168b0',
    messagingSenderId: '1057292899601',
    projectId: 'crud-project-1d07a',
    authDomain: 'crud-project-1d07a.firebaseapp.com',
    storageBucket: 'crud-project-1d07a.appspot.com',
  );

}
